### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by wiegeabo**
Various card text spelling corrections.

Also fixed the name of Kazon Guard card.

### CODE REVIEW

**Comment by FND** [comment]
Am I correct in assuming that the entire `src/data` directory is obsolete now, as recent commits have only updated `staw/data/data.json`?

**Comment by jsterner73** [comment]
No, as mentioned on the [Wiki](https://github.com/KFNEXUS/KFNEXUS.github.io/wiki) page, changes should be made on the the src files and the other files should be created with the _Grunt_ command.

**Comment by FND** [comment]
Ah, thanks for pointing that out. Your latest commit (3f06f600d9e201f1288d1fc8adf3e10d2d2e3ad5) resolves my confusion. 👍

**Comment by FND** [comment]
@jsterner73: Sorry to keep going on about this, but I've noticed that @CrazyVulcan's latest batch of changes only modified `staw-utopia/data/data.json`, but not `src/data/data.json`.

**Comment by jsterner73** [comment]
Thanks for the info, I'm currently on vacation.

@CrazyVulcan can you please look at that and check in the most recent data.json in the src/data folder as well?

**Comment by CrazyVulcan** [comment]
Yes, I can get that updated right now @Joerg Sterner

**Comment by CrazyVulcan** [comment]
I mean @jsterner73

**Pull request merged**
