### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by jsterner73**
Fixed generic Xindi Reptilian Warship name and actions.

### CODE REVIEW

**Comment by CrazyVulcan** [comment]
Dont suppose one of you would know how to set the Fleet Builder to have all the sets unchecked at first time launch? Personally I find it hard to manually uncheck everything one by one then go back and select all the sets that I own.

**Comment by jsterner73** [comment]
I'll take a look at it tomorrow.

**Comment by KFNEXUS** [comment]
I think this is not so good idea. Better to have a button "uncheck all" and "check all", but by default for newbie users sets must be checked.

**Comment by CrazyVulcan** [comment]
I see your point, but a unchecked all button would be a great addition.

**Comment by jsterner73** [comment]
I think I found a way to do the un/check all sets, but I'm struggling to "compile" the src folder and it's content to the main folder so to speak. Do you know how this is done?
I've done the changes locally so far, but I can push them if you want to give it a go.

**Comment by jsterner73** [comment]
I found the right way to do it - changes have been pushed.

**Comment by KFNEXUS** [comment]
Nice job!

**Pull request merged**
